.TH KUBEHOST 1 "September 2026" "kubehost 26.0.0" "User Commands"
.SH NAME
kubehost \- automated networking and container orchestration CLI
.SH SYNOPSIS
.B kubehost
[\fICOMMAND\fR] [\fIOPTIONS\fR]
.SH DESCRIPTION
KubeHost lets you deploy containerized apps in seconds without YAML manifests.
.SH AUTHOR
Nimul Islam Mahin <nimulmahin@gmail.com>
